# Generated by Django 3.0.4 on 2020-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userext',
            name='deleted_flg',
        ),
    ]
