# Generated by Django 3.0.4 on 2020-03-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_userext_deleted_flg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExt',
        ),
    ]
