# Generated by Django 3.0.4 on 2020-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_auto_20200411_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
